import React, { useState, useEffect } from 'react';
import {
  Card,
  Button,
  Typography,
  Tabs,
  Form,
  Input,
  Select,
  Modal,
  message,
  Table,
  Tag,
  Space,
  Badge,
  Radio,
  Tree,
  List,
  Timeline,
  Tooltip,
  Dropdown,
  Menu,
  Switch
} from 'antd';
const { Option } = Select;
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  UploadOutlined,
  DownloadOutlined,
  FilterOutlined,
  CheckCircleOutlined,
  FileTextOutlined,
  AlertOutlined,
  FileImageOutlined,
  CopyOutlined,
  EyeOutlined
} from '@ant-design/icons';
import MDEditor from '@uiw/react-md-editor';
import { v4 as uuidv4 } from 'uuid';

import storageService from '../../services/storage';
import exportImportService from '../../services/exportImportService';
import type { Character, Clue } from '../../types';

const { Title, Text } = Typography;
const { TabPane } = Tabs;
const { TextArea } = Input;

import type { OrganizerGuide as OrganizerGuideType, TruthChapter, HostingStep, ClueDistribution, FAQ, Ending } from '../../types';

const OrganizerGuide: React.FC = () => {
  // 状态管理
  const [guide, setGuide] = useState<OrganizerGuideType>({
    truthChapters: [],
    hostingSteps: [],
    clueDistributions: [],
    faqs: [],
    endings: [],
    autoGenerated: false
  });
  const [characters, setCharacters] = useState<Character[]>([]);
  const [clues, setClues] = useState<Clue[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('truth');
  const [currentProjectId, setCurrentProjectId] = useState<string>('');
  
  // 表单和编辑状态
  const [truthForm] = Form.useForm();
  const [stepForm] = Form.useForm();
  const [clueDistForm] = Form.useForm();
  const [faqForm] = Form.useForm();
  const [endingForm] = Form.useForm();
  
  // 模态框状态
  const [truthModalVisible, setTruthModalVisible] = useState(false);
  const [stepModalVisible, setStepModalVisible] = useState(false);
  const [clueDistModalVisible, setClueDistModalVisible] = useState(false);
  const [faqModalVisible, setFaqModalVisible] = useState(false);
  const [endingModalVisible, setEndingModalVisible] = useState(false);
  const [previewModalVisible, setPreviewModalVisible] = useState(false);
  const [previewContent, setPreviewContent] = useState('');
  
  // 编辑对象状态
  const [editingChapter, setEditingChapter] = useState<TruthChapter | null>(null);
  const [editingStep, setEditingStep] = useState<HostingStep | null>(null);
  const [editingClueDist, setEditingClueDist] = useState<ClueDistribution | null>(null);
  const [editingFaq, setEditingFaq] = useState<FAQ | null>(null);
  const [editingEnding, setEditingEnding] = useState<Ending | null>(null);
  
  // 定义检查结果接口
interface CheckResult {
  hasUnresolvedPoints: boolean;
  hasDurationIssues: boolean;
  hasEndingCoverageIssues: boolean;
  details: string[];
}

// 完整性检查结果
const [, setCheckResults] = useState<CheckResult>({
  hasUnresolvedPoints: false,
  hasDurationIssues: false,
  hasEndingCoverageIssues: false,
  details: []
});

  // 加载项目数据
  const loadProjectData = async (projectId: string) => {
    try {
      setIsLoading(true);
      
      // 获取项目数据
      const project = storageService.getProject(projectId);
      if (project) {
        // 获取角色数据
        setCharacters(project.characters || []);
        
        // 获取线索数据
        const allClues: Clue[] = [];
        if (project.scenes && Array.isArray(project.scenes)) {
          project.scenes.forEach(scene => {
            if (scene.clues && Array.isArray(scene.clues)) {
              allClues.push(...scene.clues);
            }
          });
        }
        setClues(allClues);
        
        // 获取组织者手册数据
        const savedGuide = project.organizerGuide || {
          truthChapters: [],
          hostingSteps: [],
          clueDistributions: [],
          faqs: [],
          endings: [],
          autoGenerated: false
        };
        setGuide(savedGuide);
        
        // 自动生成线索发放设置
      if (allClues.length > 0 && (!savedGuide.clueDistributions || savedGuide.clueDistributions.length === 0)) {
        generateClueDistributions(allClues);
      }
      }
      
      setCurrentProjectId(projectId);
    } catch (error) {
      console.error('加载项目数据失败:', error);
      message.error('加载项目数据失败');
    } finally {
      setIsLoading(false);
    }
  };

  // 初始化数据加载
  const loadData = async () => {
    setIsLoading(true);
    try {
      let projectId = storageService.getCurrentProjectId();
      if (!projectId) {
        const projects = storageService.getProjects();
        if (projects && projects.length > 0) {
          projectId = projects[0].id;
          storageService.setCurrentProjectId(projectId);
        }
      }
      
      if (projectId) {
        setCurrentProjectId(projectId);
        await loadProjectData(projectId);
      }
    } catch (error) {
      message.error('加载数据失败');
      console.error('加载数据失败:', error);
    } finally {
      setIsLoading(false);
    }
  };

  // 自动生成线索发放设置
  const generateClueDistributions = (allClues: Clue[]) => {
    const distributions: ClueDistribution[] = allClues.map(clue => ({
      clueId: clue.id,
      clueName: clue.name,
      phase: '第一幕',
      method: '公开',
      condition: '自动发放',
      notes: ''
    }));
    
    const updatedGuide = { ...guide, clueDistributions: distributions };
    setGuide(updatedGuide);
    if (currentProjectId) {
      storageService.updateProject(currentProjectId, { organizerGuide: updatedGuide });
    }
  };

  // 保存组织者手册
  const saveGuide = () => {
    if (currentProjectId) {
      storageService.updateProject(currentProjectId, { organizerGuide: guide });
      message.success('保存成功');
    }
  };

  // 自动生成手册
  const generateGuide = async () => {
    setIsLoading(true);
    try {
      // 这里可以实现智能生成逻辑
      // 目前使用基础模板生成
      const generatedGuide: OrganizerGuideType = {
        truthChapters: [
          {
            id: uuidv4(),
            title: '故事背景',
            content: '# 故事背景\n\n请在此填写故事的背景介绍。',
            relatedCharacters: [],
            relatedClues: []
          },
          {
            id: uuidv4(),
            title: '核心谜题',
            content: '# 核心谜题\n\n请在此填写案件的核心谜题。',
            relatedCharacters: [],
            relatedClues: []
          },
          {
            id: uuidv4(),
            title: '真相揭示',
            content: '# 真相揭示\n\n请在此填写完整的真相。',
            relatedCharacters: [],
            relatedClues: []
          }
        ],
        hostingSteps: [
          {
            id: uuidv4(),
            title: '游戏准备',
            duration: 30,
            hostAction: '介绍游戏背景和规则',
            playerTasks: ['阅读角色剧本', '熟悉角色设定'],
            order: 1,
            phase: '准备阶段'
          },
          {
            id: uuidv4(),
            title: '第一幕剧情',
            duration: 60,
            hostAction: '引导玩家进入第一幕剧情',
            playerTasks: ['自我介绍', '分享初步信息'],
            order: 2,
            phase: '第一幕'
          },
          {
            id: uuidv4(),
            title: '第一轮搜证',
            duration: 45,
            hostAction: '发放第一轮线索',
            playerTasks: ['分析线索', '质疑他人'],
            order: 3,
            phase: '第一幕'
          },
          {
            id: uuidv4(),
            title: '第二幕剧情',
            duration: 60,
            hostAction: '引导玩家进入第二幕剧情',
            playerTasks: ['深入探索', '挖掘秘密'],
            order: 4,
            phase: '第二幕'
          },
          {
            id: uuidv4(),
            title: '第二轮搜证',
            duration: 45,
            hostAction: '发放第二轮线索',
            playerTasks: ['整合信息', '推理真相'],
            order: 5,
            phase: '第二幕'
          },
          {
            id: uuidv4(),
            title: '最终推理',
            duration: 60,
            hostAction: '组织最终推理',
            playerTasks: ['提出指控', '解释动机'],
            order: 6,
            phase: '最终阶段'
          },
          {
            id: uuidv4(),
            title: '真相揭示',
            duration: 30,
            hostAction: '揭示真相',
            playerTasks: ['聆听真相', '回顾游戏'],
            order: 7,
            phase: '结束阶段'
          }
        ],
        clueDistributions: guide.clueDistributions,
        faqs: [
          {
            id: uuidv4(),
            question: '玩家提问如何处理？',
            answer: '根据游戏进程适当引导，不要过早透露关键信息。',
            category: '规则',
            isCommon: true
          },
          {
            id: uuidv4(),
            question: '时间控制技巧？',
            answer: '关键环节可设置定时器，确保游戏按时推进。',
            category: '规则',
            isCommon: true
          }
        ],
        endings: [
          {
            id: uuidv4(),
            title: '完美结局',
            content: '# 完美结局\n\n玩家成功找出真凶，正义得到伸张。',
            conditions: '玩家正确指认真凶且动机推理正确',
            priority: 1,
            charactersInvolved: [],
            isDefault: true
          },
          {
            id: uuidv4(),
            title: '失败结局',
            content: '# 失败结局\n\n真凶逃脱，案件成为悬案。',
            conditions: '玩家未能指认真凶',
            priority: 2,
            charactersInvolved: [],
            isDefault: false
          }
        ],
        autoGenerated: true,
        lastGenerated: new Date().toISOString()
      };
      
      // 如果有角色和线索，自动关联
      if (characters.length > 0) {
        if (generatedGuide.truthChapters && generatedGuide.truthChapters[2]) {
          generatedGuide.truthChapters[2].relatedCharacters = characters.slice(0, 3).map(c => c.id);
        }
      }
      
      if (clues.length > 0) {
        if (generatedGuide.truthChapters && generatedGuide.truthChapters[2]) {
          generatedGuide.truthChapters[2].relatedClues = clues.slice(0, 5).map(c => c.id);
        }
      }
      
      setGuide(generatedGuide);
      if (currentProjectId) {
        storageService.updateProject(currentProjectId, { organizerGuide: generatedGuide });
      }
      message.success('自动生成手册成功');
    } catch (error) {
      message.error('自动生成手册失败');
      console.error('自动生成手册失败:', error);
    } finally {
      setIsLoading(false);
    }
  };

  // 完整性检查
  const checkCompleteness = () => {
    const results: CheckResult = {
      hasUnresolvedPoints: false,
      hasDurationIssues: false,
      hasEndingCoverageIssues: false,
      details: []
    };
    
    // 检查未解释的疑点
    if (!guide.truthChapters || guide.truthChapters.length === 0) {
      results.hasUnresolvedPoints = true;
      results.details.push('真相解析章节为空，请添加真相内容');
    } else {
      const totalContentLength = guide.truthChapters.reduce((sum, chapter) => {
        return sum + (chapter.content?.length || 0) + 
               (chapter.children?.reduce((childSum, child) => childSum + (child.content?.length || 0), 0) || 0);
      }, 0);
      if (totalContentLength < 500) {
        results.hasUnresolvedPoints = true;
        results.details.push('真相解析内容过少，可能存在未解释的疑点');
      }
    }
    
    // 检查流程时长合理性
    const totalDuration = (guide.hostingSteps || []).reduce((sum, step) => sum + (step.duration || 0), 0);
    if (totalDuration < 180 || totalDuration > 480) {
      results.hasDurationIssues = true;
      if (totalDuration < 180) {
        results.details.push(`总时长过短（${totalDuration}分钟），建议游戏总时长不少于3小时`);
      } else {
        results.details.push(`总时长过长（${totalDuration}分钟），建议控制在6-8小时内`);
      }
    }
    
    // 检查结局覆盖范围
    if (!guide.endings || guide.endings.length === 0) {
      results.hasEndingCoverageIssues = true;
      results.details.push('未设置任何结局，请至少添加一个结局');
    } else if (guide.endings.length < 3) {
      results.hasEndingCoverageIssues = true;
      results.details.push('结局数量较少，建议增加更多可能性');
    }
    
    setCheckResults(results);
    
    if (results.details.length > 0) {
      Modal.info({
        title: '完整性检查结果',
        content: (
          <div>
            {results.details.map((detail, index) => (
              <p key={index}>{index + 1}. {detail}</p>
            ))}
          </div>
        )
      });
    } else {
      message.success('手册完整性良好！');
    }
  };

  // 导出功能
  const exportGuide = async (type: 'pdf' | 'cards' | 'truthTable') => {
    if (!currentProjectId) {
      message.error('请先选择项目');
      return;
    }
    
    try {
      setIsLoading(true);
      const project = storageService.getProject(currentProjectId);
      
      if (!project) {
        message.error('项目不存在');
        return;
      }
      
      if (type === 'pdf') {
      // 导出完整主持人手册PDF
      await exportImportService.exportOrganizerGuideAsPDF(project.id);
      message.success('主持人手册PDF导出成功');
    } else if (type === 'cards') {
      // 导出主持流程卡片
      await exportImportService.exportHostingCardsPDF(project.id);
      message.success('主持流程卡片导出成功');
    } else if (type === 'truthTable') {
      // 导出真相揭示表
      await exportImportService.exportTruthTablePDF(project.id);
      message.success('真相揭示表导出成功');
    }
    } catch (error) {
      console.error('导出失败:', error);
      message.error('导出失败，请重试');
    } finally {
      setIsLoading(false);
    }
  };

  // 真相章节管理
  const showTruthModal = (chapter?: TruthChapter) => {
    if (chapter) {
      setEditingChapter(chapter);
      truthForm.setFieldsValue(chapter);
    } else {
      setEditingChapter(null);
      truthForm.resetFields();
    }
    setTruthModalVisible(true);
  };

  const handleTruthSave = () => {
    truthForm.validateFields().then(values => {
      const updatedChapters = [...(guide.truthChapters || [])];
      
      if (editingChapter) {
        // 更新现有章节
        const index = updatedChapters.findIndex(c => c.id === editingChapter.id);
        if (index !== -1) {
          updatedChapters[index] = { ...values, id: editingChapter.id };
        }
      } else {
        // 添加新章节
        updatedChapters.push({ ...values, id: uuidv4() });
      }
      
      const updatedGuide = { ...guide, truthChapters: updatedChapters };
      setGuide(updatedGuide);
      saveGuide();
      setTruthModalVisible(false);
    });
  };

  const handleTruthDelete = (id: string) => {
    Modal.confirm({
      title: '确认删除',
      content: '确定要删除这个章节吗？',
      onOk: () => {
        const updatedChapters = (guide.truthChapters || []).filter(c => c.id !== id);
        const updatedGuide = { ...guide, truthChapters: updatedChapters };
        setGuide(updatedGuide);
        saveGuide();
        message.success('删除成功');
      }
    });
  };

  // 主持流程管理
  const showStepModal = (step?: HostingStep) => {
    if (step) {
      setEditingStep(step);
      stepForm.setFieldsValue(step);
    } else {
      setEditingStep(null);
      stepForm.resetFields();
    }
    setStepModalVisible(true);
  };

  const handleStepSave = () => {
    stepForm.validateFields().then(values => {
      const updatedSteps = [...(guide.hostingSteps || [])];
      
      if (editingStep) {
        // 更新现有步骤
        const index = updatedSteps.findIndex(s => s.id === editingStep.id);
        if (index !== -1) {
          updatedSteps[index] = { ...values, id: editingStep.id };
        }
      } else {
        // 添加新步骤
        const newOrder = updatedSteps.length > 0 
          ? Math.max(...updatedSteps.map(s => s.order || 0)) + 1 
          : 1;
        updatedSteps.push({ ...values, id: uuidv4(), order: newOrder });
      }
      
      // 按顺序排序
      updatedSteps.sort((a, b) => (a.order || 0) - (b.order || 0));
      
      const updatedGuide = { ...guide, hostingSteps: updatedSteps };
      setGuide(updatedGuide);
      saveGuide();
      setStepModalVisible(false);
    });
  };

  const handleStepDelete = (id: string) => {
    Modal.confirm({
      title: '确认删除',
      content: '确定要删除这个步骤吗？',
      onOk: () => {
        const updatedSteps = (guide.hostingSteps || []).filter(s => s.id !== id);
        // 重新排序
        updatedSteps.forEach((step, index) => {
          step.order = index + 1;
        });
        const updatedGuide = { ...guide, hostingSteps: updatedSteps };
        setGuide(updatedGuide);
        saveGuide();
        message.success('删除成功');
      }
    });
  };

  // 线索发放管理
  const showClueDistModal = (distribution?: ClueDistribution) => {
    if (distribution) {
      setEditingClueDist(distribution);
      clueDistForm.setFieldsValue(distribution);
    } else {
      setEditingClueDist(null);
      clueDistForm.resetFields();
    }
    setClueDistModalVisible(true);
  };

  const handleClueDistSave = () => {
    clueDistForm.validateFields().then(values => {
      const updatedDistributions = [...(guide.clueDistributions || [])];
      
      if (editingClueDist) {
        // 更新现有发放设置
        const index = updatedDistributions.findIndex(d => d.clueId === editingClueDist.clueId);
        if (index !== -1) {
          updatedDistributions[index] = values;
        }
      } else {
        // 添加新发放设置
        updatedDistributions.push({ ...values });
      }
      
      const updatedGuide = { ...guide, clueDistributions: updatedDistributions };
      setGuide(updatedGuide);
      saveGuide();
      setClueDistModalVisible(false);
    });
  };

  // 常见问题管理
  const showFaqModal = (faq?: FAQ) => {
    if (faq) {
      setEditingFaq(faq);
      faqForm.setFieldsValue(faq);
    } else {
      setEditingFaq(null);
      faqForm.resetFields();
    }
    setFaqModalVisible(true);
  };

  const handleFaqSave = () => {
    faqForm.validateFields().then(values => {
      const updatedFaqs = [...(guide.faqs || [])];
      
      if (editingFaq) {
        // 更新现有FAQ
        const index = updatedFaqs.findIndex(f => f.id === editingFaq.id);
        if (index !== -1) {
          updatedFaqs[index] = { ...values, id: editingFaq.id };
        }
      } else {
        // 添加新FAQ
        updatedFaqs.push({ ...values, id: uuidv4() });
      }
      
      const updatedGuide = { ...guide, faqs: updatedFaqs };
      setGuide(updatedGuide);
      saveGuide();
      setFaqModalVisible(false);
    });
  };

  const handleFaqDelete = (id: string) => {
    Modal.confirm({
      title: '确认删除',
      content: '确定要删除这个问题吗？',
      onOk: () => {
        const updatedFaqs = (guide.faqs || []).filter(f => f.id !== id);
        const updatedGuide = { ...guide, faqs: updatedFaqs };
        setGuide(updatedGuide);
        saveGuide();
        message.success('删除成功');
      }
    });
  };

  // 结局管理
  const showEndingModal = (ending?: Ending) => {
    if (ending) {
      setEditingEnding(ending);
      endingForm.setFieldsValue(ending);
    } else {
      setEditingEnding(null);
      endingForm.resetFields();
    }
    setEndingModalVisible(true);
  };

  const handleEndingSave = () => {
    endingForm.validateFields().then(values => {
      let updatedEndings = [...(guide.endings || [])];
      
      // 如果设置为默认结局，将其他结局设为非默认
      if (values.isDefault) {
        updatedEndings = updatedEndings.map(e => ({ ...e, isDefault: false }));
      }
      
      if (editingEnding) {
        // 更新现有结局
        const index = updatedEndings.findIndex(e => e.id === editingEnding.id);
        if (index !== -1) {
          updatedEndings[index] = { ...values, id: editingEnding.id };
        }
      } else {
        // 添加新结局
        const newPriority = updatedEndings.length > 0 
          ? Math.max(...updatedEndings.map(e => e.priority || 0)) + 1 
          : 1;
        updatedEndings.push({ ...values, id: uuidv4(), priority: newPriority });
      }
      
      // 按优先级排序
      updatedEndings.sort((a, b) => (a.priority || 0) - (b.priority || 0));
      
      const updatedGuide = { ...guide, endings: updatedEndings };
      setGuide(updatedGuide);
      saveGuide();
      setEndingModalVisible(false);
    });
  };

  const handleEndingDelete = (id: string) => {
    Modal.confirm({
      title: '确认删除',
      content: '确定要删除这个结局吗？',
      onOk: () => {
        const updatedEndings = (guide.endings || []).filter(e => e.id !== id);
        // 重新排序优先级
        updatedEndings.forEach((ending, index) => {
          ending.priority = index + 1;
        });
        const updatedGuide = { ...guide, endings: updatedEndings };
        setGuide(updatedGuide);
        saveGuide();
        message.success('删除成功');
      }
    });
  };



  // 预览结局
  const previewEnding = (content: string) => {
    setPreviewContent(content);
    setPreviewModalVisible(true);
  };

  // 构建真相章节树形数据
  const buildTruthTreeData = (chapters: TruthChapter[]): any[] => {
    return chapters.map(chapter => ({
      title: (
        <Space>
          {chapter.title}
          <Tooltip title="编辑">
            <EditOutlined 
              onClick={(e) => {
                e.stopPropagation();
                showTruthModal(chapter);
              }} 
              style={{ cursor: 'pointer', fontSize: 14 }}
            />
          </Tooltip>
          <Tooltip title="删除">
            <DeleteOutlined 
              onClick={(e) => {
                e.stopPropagation();
                handleTruthDelete(chapter.id);
              }} 
              style={{ cursor: 'pointer', fontSize: 14 }} 
            />
          </Tooltip>
        </Space>
      ),
      key: chapter.id,
      children: chapter.children ? buildTruthTreeData(chapter.children) : undefined
    }));
  };

  // 线索发放表格列配置
  const clueDistColumns = [
    {
      title: '线索名称',
      dataIndex: 'clueName',
      key: 'clueName',
      render: (text: string) => <Text ellipsis>{text}</Text>
    },
    {
      title: '发放幕次',
      dataIndex: 'phase',
      key: 'phase'
    },
    {
      title: '发放方式',
      dataIndex: 'method',
      key: 'method',
      render: (text: string) => (
        <Tag color={text === '公开' ? 'green' : text === '单独' ? 'blue' : 'orange'}>
          {text}
        </Tag>
      )
    },
    {
      title: '条件',
      dataIndex: 'condition',
      key: 'condition',
      render: (text: string) => <Text ellipsis>{text}</Text>
    },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: ClueDistribution) => (
        <Button 
          type="link" 
          icon={<EditOutlined />} 
          onClick={() => showClueDistModal(record)}
        >
          编辑
        </Button>
      )
    }
  ];

  // 初始化加载数据
  useEffect(() => {
    loadData();
  }, []);

  // 计算总时长
  const totalDuration = (guide.hostingSteps || []).reduce((sum, step) => sum + (step.duration || 0), 0);

  // 渲染真相解析标签页
  const renderTruthTab = () => (
    <Card>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <Title level={4}>真相解析</Title>
        <Button 
          type="primary" 
          icon={<PlusOutlined />} 
          onClick={() => showTruthModal()}
        >
          添加章节
        </Button>
      </div>
      
      {(guide.truthChapters || []).length > 0 ? (
        <Tree
            defaultExpandAll
            treeData={buildTruthTreeData(guide.truthChapters || [])}
            draggable
            onDrop={() => {
              // 实现拖拽排序逻辑
              message.info('拖拽排序功能开发中');
            }}
          />
      ) : (
        <div style={{ textAlign: 'center', padding: 40, color: '#999' }}>
          <Text>暂无真相章节，请点击上方按钮添加</Text>
        </div>
      )}
    </Card>
  );

  // 渲染主持流程标签页
  const renderHostingTab = () => (
    <Card>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <div>
          <Title level={4}>主持流程</Title>
          <Text type="secondary">总时长：{totalDuration}分钟 ({Math.floor(totalDuration / 60)}小时{totalDuration % 60}分钟)</Text>
        </div>
        <Button 
          type="primary" 
          icon={<PlusOutlined />} 
          onClick={() => showStepModal()}
        >
          添加步骤
        </Button>
      </div>
      
      {(guide.hostingSteps || []).length > 0 ? (
        <Timeline
          items={(guide.hostingSteps || []).map(step => ({
            color: step.phase.includes('准备') ? 'blue' : 
                  step.phase.includes('第一幕') ? 'green' :
                  step.phase.includes('第二幕') ? 'orange' :
                  step.phase.includes('最终') ? 'red' : 'purple',
            children: (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <Space>
                    <strong>{step.title}</strong>
                    <Tag color="blue">{step.duration}分钟</Tag>
                    <Tag>{step.phase}</Tag>
                  </Space>
                  <Space>
                    <Button 
                      size="small" 
                      icon={<EditOutlined />} 
                      onClick={() => showStepModal(step)}
                    >
                      编辑
                    </Button>
                    <Button 
                      size="small" 
                      danger 
                      icon={<DeleteOutlined />} 
                      onClick={() => handleStepDelete(step.id)}
                    >
                      删除
                    </Button>
                  </Space>
                </div>
                <div style={{ marginTop: 8 }}>
                  <p><Text type="secondary">主持动作：</Text>{step.hostAction}</p>
                  <p><Text type="secondary">玩家任务：</Text></p>
                  <ul>
                    {(step.playerTasks || []).map((task, index) => (
                      <li key={index}>{task}</li>
                    ))}
                  </ul>
                </div>
              </div>
            )
          }))}
        />
      ) : (
        <div style={{ textAlign: 'center', padding: 40, color: '#999' }}>
          <Text>暂无主持步骤，请点击上方按钮添加</Text>
        </div>
      )}
    </Card>
  );

  // 渲染线索发放标签页
  const renderClueDistributionTab = () => (
    <Card>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <Title level={4}>线索发放</Title>
        <Button 
          icon={<FilterOutlined />} 
          onClick={() => message.info('批量编辑功能开发中')}
        >
          批量编辑
        </Button>
      </div>
      
      {(guide.clueDistributions || []).length > 0 ? (
        <Table
          columns={clueDistColumns}
          dataSource={guide.clueDistributions || []}
          rowKey="clueId"
          pagination={{
            pageSize: 10,
            showSizeChanger: true,
            showTotal: (total) => `共 ${total} 条线索`
          }}
        />
      ) : (
        <div style={{ textAlign: 'center', padding: 40, color: '#999' }}>
          <Text>暂无线索发放设置</Text>
        </div>
      )}
    </Card>
  );

  // 渲染常见问题标签页
  const renderFaqTab = () => (
    <Card>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <Title level={4}>常见问题</Title>
        <Button 
          type="primary" 
          icon={<PlusOutlined />} 
          onClick={() => showFaqModal()}
        >
          添加问题
        </Button>
      </div>
      
      <List
        itemLayout="vertical"
        dataSource={guide.faqs}
        renderItem={faq => (
          <Card 
            style={{ marginBottom: 16 }}
            extra={
              <Space>
                <Tooltip title={faq.isCommon ? "常见问题" : "一般问题"}>
                  {faq.isCommon && <Badge dot color="red" />}
                </Tooltip>
                <Button 
                  type="link" 
                  icon={<EditOutlined />} 
                  onClick={() => showFaqModal(faq)}
                />
                <Button 
                  type="link" 
                  danger 
                  icon={<DeleteOutlined />} 
                  onClick={() => handleFaqDelete(faq.id)}
                />
              </Space>
            }
          >
            <Card.Meta
              title={
                <Space>
                  <Text strong>{faq.question}</Text>
                  <Tag color={
                    faq.category === '剧情' ? 'blue' :
                    faq.category === '规则' ? 'green' :
                    faq.category === '角色' ? 'orange' : 'purple'
                  }>
                    {faq.category}
                  </Tag>
                </Space>
              }
              description={faq.answer}
            />
          </Card>
        )}
        pagination={{
          pageSize: 5,
          showSizeChanger: true,
          showTotal: (total) => `共 ${total} 个问题`
        }}
      />
    </Card>
  );

  // 渲染结局管理标签页
  const renderEndingsTab = () => (
    <Card>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <Title level={4}>结局管理</Title>
        <Button 
          type="primary" 
          icon={<PlusOutlined />} 
          onClick={() => showEndingModal()}
        >
          添加结局
        </Button>
      </div>
      
      <List
        dataSource={guide.endings}
        renderItem={ending => (
          <Card 
            style={{ marginBottom: 16 }}
            actions={[
              <Button 
                type="link" 
                icon={<EditOutlined />} 
                onClick={() => showEndingModal(ending)}
              >
                编辑
              </Button>,
              <Button 
                type="link" 
                icon={<EyeOutlined />} 
                onClick={() => previewEnding(ending.content)}
              >
                预览
              </Button>,
              <Button 
                type="link" 
                danger 
                icon={<DeleteOutlined />} 
                onClick={() => handleEndingDelete(ending.id)}
              >
                删除
              </Button>
            ]}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
              <Space>
                <Text strong style={{ fontSize: 18 }}>{ending.title}</Text>
                {ending.isDefault && <Tag color="red">默认结局</Tag>}
                <Tag color="blue">优先级: {ending.priority}</Tag>
              </Space>
            </div>
            <div style={{ marginBottom: 8 }}>
              <Text type="secondary">触发条件：</Text>
              <Text>{ending.conditions}</Text>
            </div>
            <Text type="secondary">涉及角色：</Text>
            <div style={{ marginBottom: 8 }}>
              <Space>
                {(ending.charactersInvolved || []).map(charId => {
                  const character = characters.find(c => c.id === charId);
                  return character ? <Tag key={charId}>{character.name}</Tag> : null;
                })}
              </Space>
            </div>
            <div>
              <Text type="secondary">结局内容：</Text>
              <Text ellipsis>{ending.content.replace(/#/g, '').replace(/\n/g, ' ')}</Text>
            </div>
          </Card>
        )}
      />
    </Card>
  );

  // 真相章节编辑模态框
  const renderTruthModal = () => (
    <Modal
      title={editingChapter ? '编辑真相章节' : '添加真相章节'}
      open={truthModalVisible}
      onOk={handleTruthSave}
      onCancel={() => setTruthModalVisible(false)}
      width={800}
      destroyOnClose
    >
      <Form form={truthForm} layout="vertical">
        <Form.Item name="title" label="章节标题" rules={[{ required: true, message: '请输入章节标题' }]}>
          <Input placeholder="请输入章节标题" />
        </Form.Item>
        
        <Form.Item name="content" label="章节内容" rules={[{ required: true, message: '请输入章节内容' }]}>
          <div style={{ border: '1px solid #d9d9d9', borderRadius: 4 }}>
            <MDEditor
              value={truthForm.getFieldValue('content') || ''}
              onChange={(value) => truthForm.setFieldsValue({ content: value || '' })}
              height={300}
            />
          </div>
        </Form.Item>
        
        <Form.Item name="relatedCharacters" label="关联角色">
          <Select mode="multiple" placeholder="选择关联角色">
            {characters.map(character => (
              <Option key={character.id} value={character.id}>{character.name}</Option>
            ))}
          </Select>
        </Form.Item>
        
        <Form.Item name="relatedClues" label="关联线索">
          <Select mode="multiple" placeholder="选择关联线索">
            {clues.map(clue => (
              <Option key={clue.id} value={clue.id}>{clue.name}</Option>
            ))}
          </Select>
        </Form.Item>
      </Form>
    </Modal>
  );

  // 主持步骤编辑模态框
  const renderStepModal = () => (
    <Modal
      title={editingStep ? '编辑主持步骤' : '添加主持步骤'}
      open={stepModalVisible}
      onOk={handleStepSave}
      onCancel={() => setStepModalVisible(false)}
      width={600}
      destroyOnClose
    >
      <Form form={stepForm} layout="vertical">
        <Form.Item name="title" label="步骤标题" rules={[{ required: true, message: '请输入步骤标题' }]}>
          <Input placeholder="请输入步骤标题" />
        </Form.Item>
        
        <Form.Item name="duration" label="时长（分钟）" rules={[{ required: true, message: '请输入时长' }]}>
          <Input type="number" placeholder="请输入时长（分钟）" min={1} />
        </Form.Item>
        
        <Form.Item name="phase" label="所属阶段" rules={[{ required: true, message: '请选择所属阶段' }]}>
          <Select placeholder="请选择所属阶段">
            <Option value="准备阶段">准备阶段</Option>
            <Option value="第一幕">第一幕</Option>
            <Option value="第二幕">第二幕</Option>
            <Option value="第三幕">第三幕</Option>
            <Option value="最终阶段">最终阶段</Option>
            <Option value="结束阶段">结束阶段</Option>
          </Select>
        </Form.Item>
        
        <Form.Item name="hostAction" label="主持动作" rules={[{ required: true, message: '请输入主持动作' }]}>
          <TextArea placeholder="请输入主持动作" rows={3} />
        </Form.Item>
        
        <Form.Item name="playerTasks" label="玩家任务" rules={[{ required: true, message: '请输入玩家任务' }]}>
          <Select mode="tags" placeholder="请输入玩家任务（回车添加）" />
        </Form.Item>
      </Form>
    </Modal>
  );

  // 线索发放编辑模态框
  const renderClueDistModal = () => (
    <Modal
      title={editingClueDist ? '编辑线索发放设置' : '添加线索发放设置'}
      open={clueDistModalVisible}
      onOk={handleClueDistSave}
      onCancel={() => setClueDistModalVisible(false)}
      width={600}
      destroyOnClose
    >
      <Form form={clueDistForm} layout="vertical">
        {!editingClueDist && (
          <Form.Item name="clueId" label="选择线索" rules={[{ required: true, message: '请选择线索' }]}>
            <Select placeholder="请选择线索" onChange={(value) => {
              const selectedClue = clues.find(c => c.id === value);
              if (selectedClue) {
                clueDistForm.setFieldsValue({ clueName: selectedClue.name });
              }
            }}>
              {clues.map(clue => (
                <Option key={clue.id} value={clue.id}>{clue.name}</Option>
              ))}
            </Select>
          </Form.Item>
        )}
        
        <Form.Item name="clueName" label="线索名称" hidden={!editingClueDist}>
          <Input placeholder="线索名称" disabled={!!editingClueDist} />
        </Form.Item>
        
        <Form.Item name="phase" label="发放幕次" rules={[{ required: true, message: '请选择发放幕次' }]}>
          <Select placeholder="请选择发放幕次">
            <Option value="开场">开场</Option>
            <Option value="第一幕">第一幕</Option>
            <Option value="第二幕">第二幕</Option>
            <Option value="第三幕">第三幕</Option>
            <Option value="最终阶段">最终阶段</Option>
          </Select>
        </Form.Item>
        
        <Form.Item name="method" label="发放方式" rules={[{ required: true, message: '请选择发放方式' }]}>
          <Radio.Group>
            <Radio value="公开">公开</Radio>
            <Radio value="单独">单独</Radio>
            <Radio value="隐藏">隐藏</Radio>
          </Radio.Group>
        </Form.Item>
        
        <Form.Item name="condition" label="发放条件" rules={[{ required: true, message: '请输入发放条件' }]}>
          <TextArea placeholder="请输入发放条件" rows={2} />
        </Form.Item>
        
        <Form.Item name="notes" label="备注">
          <TextArea placeholder="请输入备注信息" rows={2} />
        </Form.Item>
      </Form>
    </Modal>
  );

  // 常见问题编辑模态框
  const renderFaqModal = () => (
    <Modal
      title={editingFaq ? '编辑常见问题' : '添加常见问题'}
      open={faqModalVisible}
      onOk={handleFaqSave}
      onCancel={() => setFaqModalVisible(false)}
      width={600}
      destroyOnClose
    >
      <Form form={faqForm} layout="vertical">
        <Form.Item name="question" label="问题" rules={[{ required: true, message: '请输入问题' }]}>
          <Input placeholder="请输入问题" />
        </Form.Item>
        
        <Form.Item name="answer" label="答案" rules={[{ required: true, message: '请输入答案' }]}>
          <TextArea placeholder="请输入答案" rows={4} />
        </Form.Item>
        
        <Form.Item name="category" label="分类" rules={[{ required: true, message: '请选择分类' }]}>
          <Select placeholder="请选择分类">
            <Option value="剧情">剧情</Option>
            <Option value="规则">规则</Option>
            <Option value="角色">角色</Option>
            <Option value="其他">其他</Option>
          </Select>
        </Form.Item>
        
        <Form.Item name="characterId" label="关联角色">
          <Select placeholder="选择关联角色（可选）">
            <Option value="">无关联角色</Option>
            {characters.map(character => (
              <Option key={character.id} value={character.id}>{character.name}</Option>
            ))}
          </Select>
        </Form.Item>
        
        <Form.Item name="isCommon" valuePropName="checked" label="标记为常见问题">
          <Switch />
        </Form.Item>
      </Form>
    </Modal>
  );

  // 结局编辑模态框
  const renderEndingModal = () => (
    <Modal
      title={editingEnding ? '编辑结局' : '添加结局'}
      open={endingModalVisible}
      onOk={handleEndingSave}
      onCancel={() => setEndingModalVisible(false)}
      width={800}
      destroyOnClose
    >
      <Form form={endingForm} layout="vertical">
        <Form.Item name="title" label="结局标题" rules={[{ required: true, message: '请输入结局标题' }]}>
          <Input placeholder="请输入结局标题" />
        </Form.Item>
        
        <Form.Item name="content" label="结局内容" rules={[{ required: true, message: '请输入结局内容' }]}>
          <div style={{ border: '1px solid #d9d9d9', borderRadius: 4 }}>
            <MDEditor
              value={endingForm.getFieldValue('content') || ''}
              onChange={(value) => endingForm.setFieldsValue({ content: value || '' })}
              height={300}
            />
          </div>
        </Form.Item>
        
        <Form.Item name="conditions" label="触发条件" rules={[{ required: true, message: '请输入触发条件' }]}>
          <TextArea placeholder="请输入触发条件" rows={3} />
        </Form.Item>
        
        <Form.Item name="charactersInvolved" label="涉及角色">
          <Select mode="multiple" placeholder="选择涉及角色">
            {characters.map(character => (
              <Option key={character.id} value={character.id}>{character.name}</Option>
            ))}
          </Select>
        </Form.Item>
        
        <Form.Item name="isDefault" valuePropName="checked" label="设为默认结局">
          <Switch />
        </Form.Item>
      </Form>
    </Modal>
  );

  // 结局预览模态框
  const renderPreviewModal = () => (
    <Modal
      title="结局预览"
      open={previewModalVisible}
      onCancel={() => setPreviewModalVisible(false)}
      width={800}
      footer={null}
    >
      <MDEditor.Markdown source={previewContent || ''} />
    </Modal>
  );

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}>
        <Title level={3}>组织者手册</Title>
        <Space>
          <Button 
            type="default" 
            icon={<CheckCircleOutlined />} 
            onClick={checkCompleteness}
          >
            完整性检查
          </Button>
          <Button 
            type="default" 
            icon={<UploadOutlined />} 
            onClick={generateGuide}
            loading={isLoading}
          >
            自动生成
          </Button>
          <Dropdown
            overlay={
              <Menu>
                <Menu.Item key="1" onClick={() => exportGuide('pdf')}>
                  <FileTextOutlined /> 导出完整PDF
                </Menu.Item>
                <Menu.Item key="2" onClick={() => exportGuide('cards')}>
                  <CopyOutlined /> 导出流程卡片
                </Menu.Item>
                <Menu.Item key="3" onClick={() => exportGuide('truthTable')}>
                  <FileImageOutlined /> 导出真相表
                </Menu.Item>
              </Menu>
            }
          >
            <Button type="primary" icon={<DownloadOutlined />}>
              导出
            </Button>
          </Dropdown>
        </Space>
      </div>
      
      <Tabs 
        activeKey={activeTab} 
        onChange={setActiveTab}
        tabBarExtraContent={
          <div style={{ color: '#999' }}>
            {guide.autoGenerated && (
              <Tooltip title={`最后生成时间：${guide.lastGenerated ? new Date(guide.lastGenerated).toLocaleString() : '未知'}`}>
                <Text type="secondary" style={{ marginRight: 8 }}>
                  <AlertOutlined /> 已自动生成基础内容
                </Text>
              </Tooltip>
            )}
          </div>
        }
      >
        <TabPane tab="真相解析" key="truth">
          {renderTruthTab()}
        </TabPane>
        <TabPane tab="主持流程" key="hosting">
          {renderHostingTab()}
        </TabPane>
        <TabPane tab="线索发放" key="clueDistribution">
          {renderClueDistributionTab()}
        </TabPane>
        <TabPane tab="常见问题" key="faq">
          {renderFaqTab()}
        </TabPane>
        <TabPane tab="结局管理" key="endings">
          {renderEndingsTab()}
        </TabPane>
      </Tabs>
      
      {renderTruthModal()}
      {renderStepModal()}
      {renderClueDistModal()}
      {renderFaqModal()}
      {renderEndingModal()}
      {renderPreviewModal()}
    </div>
  );
};

export default OrganizerGuide;