// 剧本杀相关类型定义
import type { ProjectConfig, ProjectMember, TestSimulationConfig, PlayerFeedback } from '../types';

// 使用type-only导出
export type { ProjectConfig, ProjectMember, TestSimulationConfig, PlayerFeedback };


// 角色类型
export interface Character {
  id: string;
  name: string;
  description: string;
  background: string;
  secrets: string[];
  relationships: Relationship[];
  imageUrl?: string;
}

// 角色关系类型
export interface Relationship {
  targetCharacterId: string;
  description: string;
  type: 'friend' | 'enemy' | 'neutral' | 'family';
}

// 场景资源类型
export interface SceneResource {
  id: string;
  name: string;
  type: string;
  url: string;
}

// 场景类型
export interface Scene {
  id: string;
  name: string;
  title: string;
  description: string;
  clues: Clue[];
  characterAppearances: string[];
  timelinePoint: string | null;
  keyEvents: string;
  settingDescription: string;
  charactersPresent?: string[];
  time?: string;
  location?: string;
}

// 线索类型
export interface Clue {
  id: string;
  name: string;
  description: string;
  foundBy?: string; // 角色ID
  relevance: 'high' | 'medium' | 'low';
}

// 组织者手册类型
export interface OrganizerGuide {
  truthChapters?: TruthChapter[];
  hostingSteps?: HostingStep[];
  clueDistributions?: ClueDistribution[];
  faqs?: FAQ[];
  endings?: Ending[];
  autoGenerated?: boolean;
  lastGenerated?: string;
}

export interface TruthChapter {
  id: string;
  title: string;
  content: string;
  relatedCharacters: string[];
  relatedClues: string[];
  children?: TruthChapter[];
}

export interface HostingStep {
  id: string;
  title: string;
  duration: number;
  hostAction: string;
  playerTasks: string[];
  order: number;
  phase: string;
}

export interface ClueDistribution {
  clueId: string;
  clueName: string;
  phase: string;
  method: '公开' | '单独' | '隐藏';
  condition: string;
  notes: string;
}

export interface FAQ {
  id: string;
  question: string;
  answer: string;
  characterId?: string;
  category: '剧情' | '规则' | '角色' | '其他';
  isCommon: boolean;
}

export interface Ending {
  id: string;
  title: string;
  content: string;
  conditions: string;
  priority: number;
  charactersInvolved: string[];
  isDefault: boolean;
}

// 故事类型
export interface Story {
  id: string;
  title: string;
  description: string;
  setting: string;
  theme: string;
  plotSummary: string;
  characters: Character[];
  scenes: Scene[];
  created: string;
  updated: string;
  organizerGuide?: OrganizerGuide;
  config?: ProjectConfig;
  sceneResources?: SceneResource[];
  storyOutline?: StoryOutline;
  testSimulationConfig?: TestSimulationConfig;
  playerFeedbacks?: PlayerFeedback[];
}

// 游戏规则类型
export interface GameRule {
  id: string;
  name: string;
  description: string;
  isActive: boolean;
}

// 故事大纲类型
export interface StoryOutline {
  synopsis: string;
  chapters: Chapter[];
  tricks: string[];
  themes: ThemeTag[];
  inspirations: Inspiration[];
}

// 章节类型
export interface Chapter {
  id: string;
  title: string;
  content: string;
  description: string;
  order: number;
  subChapters?: Chapter[];
}

// 主题标签类型
export interface ThemeTag {
  id: string;
  name: string;
  description?: string;
}

// 灵感类型
export interface Inspiration {
  id: string;
  source?: string;
  description?: string;
  content: string;
  timestamp: string;
  relevance?: 'high' | 'medium' | 'low';
}

// 用户设置类型
export interface UserSettings {
  theme: 'light' | 'dark' | 'system';
  language: 'zh-CN' | 'en-US';
  autoSave: boolean;
  fontSize: 'small' | 'medium' | 'large';
}